import { useState, useEffect, useRef, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { Card, Button, Grid, Section } from '../components/Common';
import '../styles/Pages.css';

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const MAX_FEED_EVENTS  = 50;
const POLL_INTERVAL_MS = 500;

const PHASE = {
  CONFIG:   'config',
  RUNNING:  'running',
  COMPLETE: 'complete',
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function formatTimestamp(ts) {
  if (!ts) return '';
  try {
    const d = new Date(ts.replace(' ', 'T'));
    return d.toLocaleTimeString(undefined, { hour12: false });
  } catch {
    return ts;
  }
}

function threatRowBorderColor(level) {
  if (level === 'RED')    return '#ef4444';
  if (level === 'YELLOW') return '#f97316';
  return 'transparent';
}

function friendlyClassifyError(msg) {
  if (!msg) return msg;
  const lower = msg.toLowerCase();
  if (lower.includes('feature names') || lower.includes('feature name')) {
    return 'Column mismatch: the CSV columns do not match what the model expects. ' +
      'Make sure the file was generated by CICFlowMeter with the correct column set ' +
      'for this model variant (5-class Default vs 6-class All). ' +
      'Do not rename, add, or remove columns.';
  }
  return msg;
}

// ---------------------------------------------------------------------------
// StatBox component
// ---------------------------------------------------------------------------

function StatBox({ label, value, valueColor }) {
  return (
    <div className="live-stat-box">
      <div className="live-stat-label">{label}</div>
      <div className="live-stat-value" style={valueColor ? { color: valueColor } : {}}>
        {value}
      </div>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Simulation component
// ---------------------------------------------------------------------------

function Simulation() {
  const navigate = useNavigate();

  const [phase, setPhase] = useState(PHASE.CONFIG);

  // Config
  const [datasets, setDatasets]               = useState([]);
  const [selectedDataset, setSelectedDataset] = useState(null);
  const [duration, setDuration]               = useState(120);
  const [flowRate, setFlowRate]               = useState(5);
  const [datasetsLoading, setDatasetsLoading] = useState(true);
  const [datasetsError, setDatasetsError]     = useState(null);

  // Session
  const [sessionId, setSessionId] = useState(null);
  const [error, setError]         = useState(null);

  // Running stats
  const [stats, setStats]             = useState({ flows: 0, elapsed: 0, remaining: 0, classified: 0 });
  const [threatCounts, setThreatCounts] = useState({ red: 0, yellow: 0, green: 0 });
  const [feed, setFeed]               = useState([]);

  // Complete
  const [completeData, setCompleteData] = useState(null);
  const [isLabeled, setIsLabeled]       = useState(false);

  // Poll state — stored in refs so event handlers see current values
  const pollRef         = useRef(null);   // setInterval handle
  const nextFromRef     = useRef(0);      // next event index to fetch
  const timerRef        = useRef(null);   // 1-second elapsed/remaining ticker
  const sessionStartRef = useRef(null);   // ms timestamp when session started
  const durationRef     = useRef(120);    // configured duration (s)

  // Refs that mirror running state so processEvent can read latest values
  // without stale closures (used for the complete-screen summary)
  const statsRef        = useRef({ flows: 0, elapsed: 0, remaining: 0, classified: 0 });
  const threatCountsRef = useRef({ red: 0, yellow: 0, green: 0 });

  useEffect(() => { statsRef.current = stats; }, [stats]);
  useEffect(() => { threatCountsRef.current = threatCounts; }, [threatCounts]);

  // ---------------------------------------------------------------------------
  // Load datasets on mount
  // ---------------------------------------------------------------------------

  useEffect(() => {
    setDatasetsLoading(true);
    fetch('/api/simulation/datasets')
      .then(res => {
        if (!res.ok) throw new Error(`Server returned ${res.status}`);
        return res.json();
      })
      .then(data => {
        const list = Array.isArray(data) ? data : (data.datasets ?? []);
        setDatasets(list);
      })
      .catch(err => setDatasetsError(`Failed to load datasets: ${err.message}`))
      .finally(() => setDatasetsLoading(false));
  }, []);

  // ---------------------------------------------------------------------------
  // Stop polling helper
  // ---------------------------------------------------------------------------

  const stopPolling = useCallback(() => {
    if (pollRef.current !== null) {
      clearInterval(pollRef.current);
      pollRef.current = null;
    }
  }, []);

  const stopTimer = useCallback(() => {
    if (timerRef.current !== null) {
      clearInterval(timerRef.current);
      timerRef.current = null;
    }
  }, []);

  // Cleanup on unmount
  useEffect(() => () => { stopPolling(); stopTimer(); }, [stopPolling, stopTimer]);

  // ---------------------------------------------------------------------------
  // Process a single event object
  // ---------------------------------------------------------------------------

  const processEvent = useCallback((evt) => {
    switch (evt.type) {
      case 'status': {
        const classified = evt.classified ?? evt.flows ?? 0;
        // elapsed/remaining come from the client-side timer; only update flows/classified here
        setStats(prev => ({
          ...prev,
          flows:      evt.flows ?? 0,
          classified,
        }));
        setThreatCounts(prev => ({
          ...prev,
          green: Math.max(0, classified - prev.red - prev.yellow),
        }));
        break;
      }
      case 'threat': {
        // Only increment threat counts — green is recomputed on status events, not here.
        // This prevents green from falsely decreasing between 5-second status updates.
        if (evt.level === 'RED') {
          setThreatCounts(prev => ({ ...prev, red: prev.red + 1 }));
        } else if (evt.level === 'YELLOW') {
          setThreatCounts(prev => ({ ...prev, yellow: prev.yellow + 1 }));
        }
        if (evt.level === 'RED' || evt.level === 'YELLOW') {
          setFeed(prev => {
            const next = [evt, ...prev];
            return next.length > MAX_FEED_EVENTS ? next.slice(0, MAX_FEED_EVENTS) : next;
          });
        }
        break;
      }
      case 'complete': {
        // Stop client-side timer
        if (timerRef.current) { clearInterval(timerRef.current); timerRef.current = null; }
        // Prefer backend summary counts; fall back to accumulated React state
        const tc = threatCountsRef.current;
        const st = statsRef.current;
        setCompleteData({
          flows:  evt.flows  ?? st.classified,
          red:    evt.red    ?? tc.red,
          yellow: evt.yellow ?? tc.yellow,
          green:  evt.green  ?? tc.green,
        });
        setPhase(PHASE.COMPLETE);
        stopPolling();
        break;
      }
      case 'error': {
        if (timerRef.current) { clearInterval(timerRef.current); timerRef.current = null; }
        setError(friendlyClassifyError(evt.message ?? 'Unknown error from server'));
        setPhase(PHASE.CONFIG);
        stopPolling();
        break;
      }
      default:
        break;
    }
  }, [stopPolling]);

  // ---------------------------------------------------------------------------
  // Start simulation
  // ---------------------------------------------------------------------------

  const handleStart = async () => {
    if (!selectedDataset) return;

    setError(null);
    setStats({ flows: 0, elapsed: 0, remaining: 0, classified: 0 });
    setThreatCounts({ red: 0, yellow: 0, green: 0 });
    setFeed([]);
    setCompleteData(null);
    setIsLabeled(selectedDataset.labeled === true);
    nextFromRef.current = 0;

    try {
      const res = await fetch('/api/simulation/start', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model:            selectedDataset.model,
          labeled:          selectedDataset.labeled ?? false,
          duration_seconds: duration,
          flow_rate:        flowRate,
        }),
      });

      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.detail ?? `Server returned ${res.status}`);
      }

      const data = await res.json();
      const sid  = data.session_id;
      setSessionId(sid);
      setPhase(PHASE.RUNNING);

      // Start client-side elapsed/remaining ticker (1s resolution, smooth display)
      sessionStartRef.current = Date.now();
      durationRef.current     = duration;
      timerRef.current = setInterval(() => {
        const elapsedSec = Math.floor((Date.now() - sessionStartRef.current) / 1000);
        const remainSec  = Math.max(0, durationRef.current - elapsedSec);
        setStats(prev => ({ ...prev, elapsed: elapsedSec, remaining: remainSec }));
      }, 1000);

      // Start polling /api/simulation/events/{sid}?from=N
      pollRef.current = setInterval(async () => {
        try {
          const r = await fetch(
            `/api/simulation/events/${sid}?from=${nextFromRef.current}`
          );
          if (!r.ok) return;

          const payload = await r.json();
          const { events, next_from, done } = payload;

          nextFromRef.current = next_from;

          for (const evt of events) {
            processEvent(evt);
          }

          // If done with no "complete" event, build summary from accumulated state
          if (done && !events.some(e => e.type === 'complete' || e.type === 'error')) {
            if (timerRef.current) { clearInterval(timerRef.current); timerRef.current = null; }
            const tc = threatCountsRef.current;
            const st = statsRef.current;
            setPhase(prev => {
              if (prev === PHASE.RUNNING) {
                setCompleteData({
                  flows:  st.classified,
                  red:    tc.red,
                  yellow: tc.yellow,
                  green:  tc.green,
                });
                return PHASE.COMPLETE;
              }
              return prev;
            });
            stopPolling();
          }
        } catch (pollErr) {
          console.error('Poll error:', pollErr);
        }
      }, POLL_INTERVAL_MS);

    } catch (err) {
      setError(friendlyClassifyError(err.message));
      setPhase(PHASE.CONFIG);
    }
  };

  // ---------------------------------------------------------------------------
  // Stop simulation
  // ---------------------------------------------------------------------------

  const handleStop = async () => {
    stopPolling();
    stopTimer();
    setPhase(PHASE.CONFIG);
    if (sessionId) {
      fetch(`/api/simulation/stop/${sessionId}`, { method: 'POST' }).catch(() => {});
    }
  };

  // ---------------------------------------------------------------------------
  // Reset
  // ---------------------------------------------------------------------------

  const handleReset = () => {
    stopPolling();
    stopTimer();
    setPhase(PHASE.CONFIG);
    setSessionId(null);
    setError(null);
    setStats({ flows: 0, elapsed: 0, remaining: 0, classified: 0 });
    setThreatCounts({ red: 0, yellow: 0, green: 0 });
    setFeed([]);
    setCompleteData(null);
    setIsLabeled(false);
    nextFromRef.current = 0;
  };

  // ---------------------------------------------------------------------------
  // CONFIG PANEL
  // ---------------------------------------------------------------------------

  const configPanel = (
    <div className="live-config-panel">
      <Card
        title="Configure Simulation"
        subtitle="Select a dataset and run real-time classification on simulated flows"
      >
        <div style={{ marginBottom: '1rem' }}>
          <label style={{ display: 'block', fontWeight: 500, marginBottom: '0.5rem' }}>
            Select Dataset
          </label>

          {datasetsLoading && (
            <div style={{ color: 'var(--text-secondary)', fontSize: '0.9rem' }}>Loading datasets...</div>
          )}
          {datasetsError && <div className="live-error-msg">{datasetsError}</div>}
          {!datasetsLoading && !datasetsError && datasets.length === 0 && (
            <div style={{ color: 'var(--text-secondary)', fontSize: '0.9rem' }}>No datasets found.</div>
          )}

          {!datasetsLoading && datasets.length > 0 && (
            <div className="simul-dataset-options">
              {datasets.map((ds, idx) => {
                const dsKey    = ds.name ?? ds.id ?? String(idx);
                const isSelected = selectedDataset === ds;
                const modelBadge = ds.model === 'all' ? '6 Class (All)' : '5 Class (Default)';
                const labeled  = ds.labeled === true;

                return (
                  <div
                    key={dsKey}
                    className={`simul-dataset-option${isSelected ? ' selected' : ''}`}
                    onClick={() => setSelectedDataset(ds)}
                  >
                    <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginBottom: '0.35rem' }}>
                      <input
                        type="radio"
                        name="simul-dataset"
                        readOnly
                        checked={isSelected}
                        onChange={() => setSelectedDataset(ds)}
                      />
                      <span style={{ fontWeight: 600, fontSize: '0.95rem' }}>
                        {ds.label ?? ds.name ?? dsKey}
                      </span>
                    </div>
                    <div style={{ display: 'flex', gap: '0.4rem', marginLeft: '1.5rem' }}>
                      <span className="simul-model-badge">{modelBadge}</span>
                      {labeled && <span className="simul-labeled-badge">Labeled</span>}
                    </div>
                  </div>
                );
              })}
            </div>
          )}

          <div style={{ fontSize: '0.82rem', color: 'var(--text-secondary)', marginTop: '0.5rem' }}>
            Labeled datasets include ground-truth labels for accuracy comparison.
          </div>
        </div>

        <Grid cols={2}>
          <div className="form-group">
            <label htmlFor="simul-duration">Duration (seconds)</label>
            <input
              id="simul-duration"
              type="number"
              value={duration}
              onChange={e => setDuration(Math.max(10, parseInt(e.target.value, 10) || 10))}
              min="10"
            />
          </div>
          <div className="form-group">
            <label htmlFor="simul-flowrate">Flow Rate (flows/second)</label>
            <input
              id="simul-flowrate"
              type="number"
              value={flowRate}
              onChange={e => setFlowRate(Math.min(100, Math.max(1, parseInt(e.target.value, 10) || 1)))}
              min="1"
              max="100"
            />
          </div>
        </Grid>

        {error && <div className="live-error-msg" style={{ marginBottom: '0.75rem' }}>{error}</div>}

        <div style={{ marginTop: '1rem' }}>
          <Button variant="primary" onClick={handleStart} disabled={!selectedDataset || datasetsLoading}>
            Start Simulation
          </Button>
        </div>
      </Card>
    </div>
  );

  // ---------------------------------------------------------------------------
  // RUNNING PANEL
  // ---------------------------------------------------------------------------

  const runningPanel = (
    <div className="live-running-panel">
      <div style={{ marginBottom: '1.5rem' }}>
        <Button variant="danger" onClick={handleStop}>Stop Simulation</Button>
      </div>

      <Card title="Simulation Statistics" subtitle="Flows/classified update every 5 seconds; time updates every second">
        <Grid cols={4}>
          <StatBox label="Flows Processed"    value={stats.flows.toLocaleString()} />
          <StatBox label="Time Elapsed (s)"   value={stats.elapsed.toLocaleString()} />
          <StatBox label="Threats"            value={threatCounts.red.toLocaleString()} valueColor="#ef4444" />
          <StatBox label="Time Remaining (s)" value={stats.remaining.toLocaleString()} valueColor="#f97316" />
        </Grid>
        {stats.elapsed === 0 && (
          <div style={{ marginTop: '0.75rem', fontSize: '0.85rem', color: 'var(--text-secondary)' }}>
            Initializing pipeline...
          </div>
        )}
      </Card>

      <Card title="Threat Level Breakdown" subtitle="Counts by severity">
        <Grid cols={3}>
          <div className="live-level-box live-level-red">
            <div className="live-level-label">RED — Confirmed Threats</div>
            <div className="live-level-count">{threatCounts.red}</div>
          </div>
          <div className="live-level-box live-level-yellow">
            <div className="live-level-label">YELLOW — Suspicious</div>
            <div className="live-level-count">{threatCounts.yellow}</div>
          </div>
          <div className="live-level-box live-level-green">
            <div className="live-level-label">GREEN — Clean</div>
            <div className="live-level-count">{threatCounts.green}</div>
          </div>
        </Grid>
      </Card>

      <Card title="Threat Feed" subtitle={`Last ${MAX_FEED_EVENTS} RED / YELLOW events`}>
        {feed.length === 0 ? (
          <div className="live-feed-empty" style={{ color: '#22c55e' }}>
            No threats detected so far — traffic appears clean.
          </div>
        ) : (
          <div className="live-feed-scroll">
            {feed.map((evt, idx) => (
              <div key={`${evt.timestamp ?? ''}-${evt.prediction ?? ''}-${idx}`} className="live-feed-row" style={{ borderLeftColor: threatRowBorderColor(evt.level) }}>
                <span className="live-feed-time">{formatTimestamp(evt.timestamp)}</span>
                <span className="live-feed-route">
                  {evt.src_ip && evt.dst_ip
                    ? `${evt.src_ip}:${evt.src_port ?? '?'} \u2192 ${evt.dst_ip}:${evt.dst_port ?? '?'} (Proto:${evt.protocol ?? '?'})`
                    : evt.protocol != null
                      ? `Proto:${evt.protocol}`
                      : 'Flow info N/A'}
                </span>
                <span className="live-feed-label">{evt.prediction ?? '\u2014'}</span>
                <span className="live-feed-conf">
                  {evt.confidence != null ? `${(evt.confidence * 100).toFixed(1)}%` : '\u2014'}
                </span>
                <span className={`threat-badge ${evt.level === 'RED' ? 'threat-red' : 'threat-yellow'}`}>
                  {evt.level}
                </span>
              </div>
            ))}
          </div>
        )}
      </Card>
    </div>
  );

  // ---------------------------------------------------------------------------
  // COMPLETE PANEL
  // ---------------------------------------------------------------------------

  const completePanel = completeData && (
    <div className="live-complete-panel">
      <Card title="Simulation Complete" subtitle="All flows processed">
        <Grid cols={4}>
          <StatBox label="Total Flows"        value={completeData.flows.toLocaleString()} />
          <StatBox label="Threats (RED)"      value={completeData.red.toLocaleString()}   valueColor="#ef4444" />
          <StatBox label="Suspicious (YELLOW)" value={completeData.yellow.toLocaleString()} valueColor="#f97316" />
          <StatBox label="Clean (GREEN)"      value={completeData.green.toLocaleString()} valueColor="#22c55e" />
        </Grid>

        {isLabeled && (
          <div style={{
            marginTop: '1.25rem', padding: '0.75rem 1rem',
            background: 'rgba(34,197,94,0.08)', border: '1px solid rgba(34,197,94,0.25)',
            borderRadius: '6px', fontSize: '0.88rem', color: 'var(--text-secondary)',
          }}>
            Labeled mode — accuracy data available in the Reports section.
          </div>
        )}

        <div style={{ display: 'flex', gap: '0.75rem', marginTop: '1.5rem', flexWrap: 'wrap' }}>
          {isLabeled && (
            <Button variant="success" onClick={() => navigate('/reports')}>View Report</Button>
          )}
          <Button variant="primary" onClick={handleReset}>Start New Simulation</Button>
        </div>
      </Card>
    </div>
  );

  // ---------------------------------------------------------------------------
  // Render
  // ---------------------------------------------------------------------------

  return (
    <Section title="Simulation Mode">
      {phase === PHASE.CONFIG   && configPanel}
      {phase === PHASE.RUNNING  && runningPanel}
      {phase === PHASE.COMPLETE && completePanel}
    </Section>
  );
}

export default Simulation;
